
http :
  listener:
    host: "localhost"
    port: "8084"
    path : "/{transportType}/{transportCompany}/{serviceType}"
  requester:
    host: "localhost"
    port: "8082"
    routesPath: "/fastGo/route"
    schedulePath: "/fastGo/schedule"
    
  