
http :
  listener:
    host: "0.0.0.0"
    port: "8083"
    path : "/{transportType}/{transportCompany}/{serviceType}"
  requester:
    host: "localhost"
    port: "8081"
    routesPath: "/travelOnTripCall/route"
    schedulePath: "/travelOnTripCall/schedule"
    
  